- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
  
- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Replace 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf       # File to modify
    regexp: '127.0.0.1' # Regex pattern to search
    replace: '0.0.0.0' # Text to replace with

- name: Restarting mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted 